// Code generated by protoc-gen-gogo.
// source: api.proto
// DO NOT EDIT!

/*
	Package reporting is a generated protocol buffer package.

	It is generated from these files:
		api.proto

	It has these top-level messages:
		RawEvent
*/
package reporting

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// RawEvent represents an event that happened in the system
type RawEvent struct {
	// Type is the event type such as "node accessed" or "user logged in"
	Type string `protobuf:"bytes,1,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	// Data is the JSON-encoded event payload
	Data []byte `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	// Timestamp is the Unix timestamp of the event
	Timestamp int64 `protobuf:"varint,3,opt,name=Timestamp,json=timestamp,proto3" json:"Timestamp,omitempty"`
}

func (m *RawEvent) Reset()                    { *m = RawEvent{} }
func (m *RawEvent) String() string            { return proto.CompactTextString(m) }
func (*RawEvent) ProtoMessage()               {}
func (*RawEvent) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{0} }

func init() {
	proto.RegisterType((*RawEvent)(nil), "reporting.RawEvent")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Events service

type EventsClient interface {
	// Record records the provided stream of events
	Record(ctx context.Context, opts ...grpc.CallOption) (Events_RecordClient, error)
}

type eventsClient struct {
	cc *grpc.ClientConn
}

func NewEventsClient(cc *grpc.ClientConn) EventsClient {
	return &eventsClient{cc}
}

func (c *eventsClient) Record(ctx context.Context, opts ...grpc.CallOption) (Events_RecordClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Events_serviceDesc.Streams[0], c.cc, "/reporting.Events/Record", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventsRecordClient{stream}
	return x, nil
}

type Events_RecordClient interface {
	Send(*RawEvent) error
	CloseAndRecv() (*google_protobuf1.Empty, error)
	grpc.ClientStream
}

type eventsRecordClient struct {
	grpc.ClientStream
}

func (x *eventsRecordClient) Send(m *RawEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *eventsRecordClient) CloseAndRecv() (*google_protobuf1.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(google_protobuf1.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Events service

type EventsServer interface {
	// Record records the provided stream of events
	Record(Events_RecordServer) error
}

func RegisterEventsServer(s *grpc.Server, srv EventsServer) {
	s.RegisterService(&_Events_serviceDesc, srv)
}

func _Events_Record_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventsServer).Record(&eventsRecordServer{stream})
}

type Events_RecordServer interface {
	SendAndClose(*google_protobuf1.Empty) error
	Recv() (*RawEvent, error)
	grpc.ServerStream
}

type eventsRecordServer struct {
	grpc.ServerStream
}

func (x *eventsRecordServer) SendAndClose(m *google_protobuf1.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *eventsRecordServer) Recv() (*RawEvent, error) {
	m := new(RawEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Events_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reporting.Events",
	HandlerType: (*EventsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Record",
			Handler:       _Events_Record_Handler,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptorApi,
}

func (m *RawEvent) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *RawEvent) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Type) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintApi(data, i, uint64(len(m.Type)))
		i += copy(data[i:], m.Type)
	}
	if len(m.Data) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintApi(data, i, uint64(len(m.Data)))
		i += copy(data[i:], m.Data)
	}
	if m.Timestamp != 0 {
		data[i] = 0x18
		i++
		i = encodeVarintApi(data, i, uint64(m.Timestamp))
	}
	return i, nil
}

func encodeFixed64Api(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Api(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintApi(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *RawEvent) Size() (n int) {
	var l int
	_ = l
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovApi(uint64(m.Timestamp))
	}
	return n
}

func sovApi(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozApi(x uint64) (n int) {
	return sovApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RawEvent) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RawEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RawEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], data[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Timestamp |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApi(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApi(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthApi
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowApi
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipApi(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthApi = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApi   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("api.proto", fileDescriptorApi) }

var fileDescriptorApi = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x8d, 0x5b, 0x8a, 0x0d, 0x1e, 0x24, 0x82, 0x94, 0x2a, 0xa5, 0x78, 0xea, 0xc5, 0x04,
	0xf4, 0xe0, 0x59, 0x71, 0xef, 0x52, 0xf6, 0xe4, 0x45, 0xa6, 0x6d, 0xcc, 0x06, 0x6c, 0x13, 0x92,
	0x59, 0x97, 0xbc, 0x89, 0x8f, 0xe4, 0xd1, 0x47, 0x90, 0xfa, 0x22, 0xb2, 0xfd, 0xe3, 0x6d, 0xbe,
	0xef, 0x1b, 0xe6, 0xfb, 0x0d, 0x4d, 0xc0, 0x6a, 0x6e, 0x9d, 0x41, 0xc3, 0x12, 0x27, 0xad, 0x71,
	0xa8, 0x7b, 0x95, 0xbd, 0x28, 0x8d, 0xdb, 0x5d, 0xcd, 0x1b, 0xd3, 0x09, 0xe5, 0x6c, 0x73, 0x23,
	0x1b, 0xe3, 0x83, 0x47, 0x39, 0x4b, 0x05, 0x28, 0xf7, 0x10, 0x04, 0x6e, 0xb5, 0x6b, 0x5f, 0x2d,
	0x38, 0x0c, 0x42, 0x19, 0xa3, 0xde, 0x25, 0x58, 0xed, 0xe7, 0x51, 0x80, 0xd5, 0x02, 0xfa, 0xde,
	0x20, 0xa0, 0x36, 0xbd, 0x9f, 0x6a, 0xb2, 0xcb, 0x39, 0x1d, 0x55, 0xbd, 0x7b, 0x13, 0xb2, 0xb3,
	0x18, 0xa6, 0xf0, 0xfa, 0x99, 0x9e, 0x54, 0xb0, 0x5f, 0x7f, 0xc8, 0x1e, 0x19, 0xa3, 0xd1, 0x26,
	0x58, 0x99, 0x92, 0x82, 0x94, 0x49, 0x15, 0x61, 0xb0, 0xf2, 0xe0, 0x3d, 0x01, 0x42, 0x7a, 0x5c,
	0x90, 0xf2, 0xb4, 0x8a, 0x5a, 0x40, 0x60, 0x57, 0x34, 0xd9, 0xe8, 0x4e, 0x7a, 0x84, 0xce, 0xa6,
	0xab, 0x82, 0x94, 0xab, 0x2a, 0xc1, 0xc5, 0xb8, 0x7d, 0xa0, 0xf1, 0x78, 0xce, 0xb3, 0x7b, 0x1a,
	0x57, 0xb2, 0x31, 0xae, 0x65, 0xe7, 0xfc, 0xff, 0x55, 0xbe, 0xd4, 0x65, 0x17, 0x7c, 0x02, 0xe3,
	0x0b, 0x18, 0x5f, 0x1f, 0xc0, 0x4a, 0xf2, 0x78, 0xf6, 0x35, 0xe4, 0xe4, 0x7b, 0xc8, 0xc9, 0xcf,
	0x90, 0x93, 0xcf, 0xdf, 0xfc, 0xa8, 0x8e, 0xc7, 0x9d, 0xbb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xdd, 0x93, 0x69, 0x9b, 0x3e, 0x01, 0x00, 0x00,
}
